// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RadarPncp.Api.Data;

#nullable disable

namespace RadarPncp.Api.Migrations
{
    [DbContext(typeof(RadarDbContext))]
    [Migration("20260924184048_AdotaSnakeCaseEAjustaContratacao")]
    partial class AdotaSnakeCaseEAjustaContratacao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RadarPncp.Api.Data.Entities.GovernmentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("tax_id");

                    b.HasKey("Id")
                        .HasName("pk_government_entities");

                    b.HasIndex("TaxId")
                        .IsUnique()
                        .HasDatabaseName("ix_government_entities_tax_id");

                    b.ToTable("government_entities", (string)null);
                });

            modelBuilder.Entity("RadarPncp.Api.Data.Entities.GovernmentUnit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AbbreviationName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("abbreviation_name");

                    b.Property<long>("GovernmentEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("government_entity_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PncpUnitCode")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("pncp_unit_code");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("state_code");

                    b.HasKey("Id")
                        .HasName("pk_government_units");

                    b.HasIndex("GovernmentEntityId", "PncpUnitCode")
                        .IsUnique()
                        .HasDatabaseName("ix_government_units_government_entity_id_pncp_unit_code");

                    b.ToTable("government_units", (string)null);
                });

            modelBuilder.Entity("RadarPncp.Api.Data.Entities.Procurement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DisputeType")
                        .HasColumnType("text")
                        .HasColumnName("dispute_type");

                    b.Property<decimal?>("EstimatedTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("estimated_total");

                    b.Property<long>("GovernmentUnitId")
                        .HasColumnType("bigint")
                        .HasColumnName("government_unit_id");

                    b.Property<bool>("HasParliamentaryAmendment")
                        .HasColumnType("boolean")
                        .HasColumnName("has_parliamentary_amendment");

                    b.Property<decimal?>("HomologatedTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("homologated_total");

                    b.Property<DateTime>("IngestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at");

                    b.Property<bool>("IsPriceRegistration")
                        .HasColumnType("boolean")
                        .HasColumnName("is_price_registration");

                    b.Property<string>("Legislation")
                        .HasColumnType("text")
                        .HasColumnName("legislation");

                    b.Property<int>("ModalityId")
                        .HasColumnType("integer")
                        .HasColumnName("modality_id");

                    b.Property<string>("ModalityName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modality_name");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.Property<string>("Object")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object");

                    b.Property<string>("PncpControlNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pncp_control_number");

                    b.Property<string>("ProcessNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("process_number");

                    b.Property<DateTime?>("ProposalClosureDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proposal_closure_date");

                    b.Property<DateTime?>("ProposalOpeningDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proposal_opening_date");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publish_date");

                    b.Property<string>("Publisher")
                        .HasColumnType("text")
                        .HasColumnName("publisher");

                    b.Property<int>("Sequential")
                        .HasColumnType("integer")
                        .HasColumnName("sequential");

                    b.Property<int>("SolicitationId")
                        .HasColumnType("integer")
                        .HasColumnName("solicitation_id");

                    b.Property<string>("SolicitationName")
                        .HasColumnType("text")
                        .HasColumnName("solicitation_name");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status_name");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_procurements");

                    b.HasIndex("GovernmentUnitId")
                        .HasDatabaseName("ix_procurements_government_unit_id");

                    b.HasIndex("PncpControlNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_procurements_pncp_control_number");

                    b.ToTable("procurements", (string)null);
                });

            modelBuilder.Entity("RadarPncp.Api.Data.Entities.GovernmentUnit", b =>
                {
                    b.HasOne("RadarPncp.Api.Data.Entities.GovernmentEntity", "GovernmentEntity")
                        .WithMany()
                        .HasForeignKey("GovernmentEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_government_units_government_entities_government_entity_id");

                    b.Navigation("GovernmentEntity");
                });

            modelBuilder.Entity("RadarPncp.Api.Data.Entities.Procurement", b =>
                {
                    b.HasOne("RadarPncp.Api.Data.Entities.GovernmentUnit", "GovernmentUnit")
                        .WithMany()
                        .HasForeignKey("GovernmentUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_procurements_government_units_government_unit_id");

                    b.Navigation("GovernmentUnit");
                });
#pragma warning restore 612, 618
        }
    }
}
