// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RadarPncp.Api.Data;

#nullable disable

namespace RadarPncp.Api.Migrations
{
    [DbContext(typeof(RadarDbContext))]
    partial class RadarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RadarPncp.Api.Data.Entities.GovernmentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.HasKey("Id");

                    b.HasIndex("TaxId")
                        .IsUnique();

                    b.ToTable("GovernmentEntities");
                });

            modelBuilder.Entity("RadarPncp.Api.Data.Entities.GovernmentUnit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AbbreviationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("GovernmentEntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PncpUnitCode")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("Id");

                    b.HasIndex("GovernmentEntityId", "PncpUnitCode")
                        .IsUnique();

                    b.ToTable("GovernmentUnits");
                });

            modelBuilder.Entity("RadarPncp.Api.Data.Entities.Procurement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DisputeType")
                        .HasColumnType("text");

                    b.Property<decimal?>("EstimatedTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<long>("GovernmentUnitId")
                        .HasColumnType("bigint");

                    b.Property<bool>("HasParliamentaryAmendment")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("HomologatedTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("IngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPriceRegistration")
                        .HasColumnType("boolean");

                    b.Property<string>("Legislation")
                        .HasColumnType("text");

                    b.Property<int>("ModalityId")
                        .HasColumnType("integer");

                    b.Property<string>("ModalityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Object")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PncpControlNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProcessNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProposalClosureDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProposalOpeningDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Publisher")
                        .HasColumnType("text");

                    b.Property<int>("Sequential")
                        .HasColumnType("integer");

                    b.Property<string>("SolicitationName")
                        .HasColumnType("text");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GovernmentUnitId");

                    b.HasIndex("PncpControlNumber")
                        .IsUnique();

                    b.ToTable("Procurements");
                });

            modelBuilder.Entity("RadarPncp.Api.Data.Entities.GovernmentUnit", b =>
                {
                    b.HasOne("RadarPncp.Api.Data.Entities.GovernmentEntity", null)
                        .WithMany()
                        .HasForeignKey("GovernmentEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RadarPncp.Api.Data.Entities.Procurement", b =>
                {
                    b.HasOne("RadarPncp.Api.Data.Entities.GovernmentUnit", null)
                        .WithMany()
                        .HasForeignKey("GovernmentUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
